### ISSUE TITLE
Export `populate_qflist()` publicly

### ISSUE THREAD

**Issue by gw31415** [onsails/diaglist.nvim#12]
Hello. I am always grateful for this plugin. Sorry for my poor English.

Why don't you export the local function `populate_qflist()` in `lua/diaglist/quickfix.lua` publicly?

In my case, I want to add a diaglist to the quickfix list on LspAttach events (or equivalent timing: e.g. nvim-lspconfig callback function), but I do not want to display the quickfix window at that time.

**Comment by onsails** [comment]
Sure why not, please make a PR

**Comment by onsails** [comment]
Fixed by #13
