### ISSUE TITLE
Better support for different neovim versions

### ISSUE THREAD

**Issue by JuniorSuperTux** [onsails/diaglist.nvim#8]
When I'm using Neovim V0.5, errors show saying that LSP events are not valid events. After switching to Neovim V0.6, deprecation warnings are popping up.

**Comment by onsails** [comment]
I can only support latest stable neovim which is 0.6 as I only use it.
Please show your deprecation warnings on 0.6.

**Comment by JuniorSuperTux** [comment]
The deprecation warning is as following:
```
vim.lsp.diagnostic.get_all is deprecated. See :h deprecated
```

**Comment by onsails** [comment]
> The deprecation warning is as following:
> 
> ```
> vim.lsp.diagnostic.get_all is deprecated. See :h deprecated
> ```

thanks, this now should be fixed
